// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountBound.proto

package com.guaji.game.protocol;

public final class AccountBound {
  private AccountBound() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HPAccountBoundInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code HPAccountBoundInfo}
   *
   * <pre>
   * 进入帐号绑定信息界面
   * </pre>
   */
  public static final class HPAccountBoundInfo extends
      com.google.protobuf.GeneratedMessage
      implements HPAccountBoundInfoOrBuilder {
    // Use HPAccountBoundInfo.newBuilder() to construct.
    private HPAccountBoundInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPAccountBoundInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPAccountBoundInfo defaultInstance;
    public static HPAccountBoundInfo getDefaultInstance() {
      return defaultInstance;
    }

    public HPAccountBoundInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPAccountBoundInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.class, com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<HPAccountBoundInfo> PARSER =
        new com.google.protobuf.AbstractParser<HPAccountBoundInfo>() {
      public HPAccountBoundInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPAccountBoundInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPAccountBoundInfo> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.AccountBound.HPAccountBoundInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPAccountBoundInfo}
     *
     * <pre>
     * 进入帐号绑定信息界面
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.AccountBound.HPAccountBoundInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.class, com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.Builder.class);
      }

      // Construct using com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundInfo_descriptor;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundInfo getDefaultInstanceForType() {
        return com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.getDefaultInstance();
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundInfo build() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundInfo buildPartial() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundInfo result = new com.guaji.game.protocol.AccountBound.HPAccountBoundInfo(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.AccountBound.HPAccountBoundInfo) {
          return mergeFrom((com.guaji.game.protocol.AccountBound.HPAccountBoundInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.AccountBound.HPAccountBoundInfo other) {
        if (other == com.guaji.game.protocol.AccountBound.HPAccountBoundInfo.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.AccountBound.HPAccountBoundInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.AccountBound.HPAccountBoundInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPAccountBoundInfo)
    }

    static {
      defaultInstance = new HPAccountBoundInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPAccountBoundInfo)
  }

  public interface HPAccountBoundRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 accountStatus = 1;
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    boolean hasAccountStatus();
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    int getAccountStatus();

    // required int32 accountReward = 2;
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    boolean hasAccountReward();
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    int getAccountReward();
  }
  /**
   * Protobuf type {@code HPAccountBoundRet}
   */
  public static final class HPAccountBoundRet extends
      com.google.protobuf.GeneratedMessage
      implements HPAccountBoundRetOrBuilder {
    // Use HPAccountBoundRet.newBuilder() to construct.
    private HPAccountBoundRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPAccountBoundRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPAccountBoundRet defaultInstance;
    public static HPAccountBoundRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPAccountBoundRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPAccountBoundRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountStatus_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountReward_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.AccountBound.HPAccountBoundRet.class, com.guaji.game.protocol.AccountBound.HPAccountBoundRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPAccountBoundRet> PARSER =
        new com.google.protobuf.AbstractParser<HPAccountBoundRet>() {
      public HPAccountBoundRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPAccountBoundRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPAccountBoundRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 accountStatus = 1;
    public static final int ACCOUNTSTATUS_FIELD_NUMBER = 1;
    private int accountStatus_;
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    public boolean hasAccountStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    public int getAccountStatus() {
      return accountStatus_;
    }

    // required int32 accountReward = 2;
    public static final int ACCOUNTREWARD_FIELD_NUMBER = 2;
    private int accountReward_;
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    public boolean hasAccountReward() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    public int getAccountReward() {
      return accountReward_;
    }

    private void initFields() {
      accountStatus_ = 0;
      accountReward_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, accountStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountReward_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, accountStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.AccountBound.HPAccountBoundRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPAccountBoundRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.AccountBound.HPAccountBoundRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.AccountBound.HPAccountBoundRet.class, com.guaji.game.protocol.AccountBound.HPAccountBoundRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.AccountBound.HPAccountBoundRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountReward_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundRet_descriptor;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.AccountBound.HPAccountBoundRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundRet build() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundRet buildPartial() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundRet result = new com.guaji.game.protocol.AccountBound.HPAccountBoundRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountStatus_ = accountStatus_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountReward_ = accountReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.AccountBound.HPAccountBoundRet) {
          return mergeFrom((com.guaji.game.protocol.AccountBound.HPAccountBoundRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.AccountBound.HPAccountBoundRet other) {
        if (other == com.guaji.game.protocol.AccountBound.HPAccountBoundRet.getDefaultInstance()) return this;
        if (other.hasAccountStatus()) {
          setAccountStatus(other.getAccountStatus());
        }
        if (other.hasAccountReward()) {
          setAccountReward(other.getAccountReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountStatus()) {
          
          return false;
        }
        if (!hasAccountReward()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.AccountBound.HPAccountBoundRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.AccountBound.HPAccountBoundRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 accountStatus = 1;
      private int accountStatus_ ;
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public boolean hasAccountStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public int getAccountStatus() {
        return accountStatus_;
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public Builder setAccountStatus(int value) {
        bitField0_ |= 0x00000001;
        accountStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public Builder clearAccountStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountStatus_ = 0;
        onChanged();
        return this;
      }

      // required int32 accountReward = 2;
      private int accountReward_ ;
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public boolean hasAccountReward() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public int getAccountReward() {
        return accountReward_;
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public Builder setAccountReward(int value) {
        bitField0_ |= 0x00000002;
        accountReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public Builder clearAccountReward() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountReward_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPAccountBoundRet)
    }

    static {
      defaultInstance = new HPAccountBoundRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPAccountBoundRet)
  }

  public interface HPAccountBoundConfirmOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userId = 1;
    /**
     * <code>required string userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required string wallet = 2;
    /**
     * <code>required string wallet = 2;</code>
     */
    boolean hasWallet();
    /**
     * <code>required string wallet = 2;</code>
     */
    java.lang.String getWallet();
    /**
     * <code>required string wallet = 2;</code>
     */
    com.google.protobuf.ByteString
        getWalletBytes();
  }
  /**
   * Protobuf type {@code HPAccountBoundConfirm}
   *
   * <pre>
   * 领取帐号绑定奖励
   * </pre>
   */
  public static final class HPAccountBoundConfirm extends
      com.google.protobuf.GeneratedMessage
      implements HPAccountBoundConfirmOrBuilder {
    // Use HPAccountBoundConfirm.newBuilder() to construct.
    private HPAccountBoundConfirm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPAccountBoundConfirm(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPAccountBoundConfirm defaultInstance;
    public static HPAccountBoundConfirm getDefaultInstance() {
      return defaultInstance;
    }

    public HPAccountBoundConfirm getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPAccountBoundConfirm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              wallet_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.class, com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.Builder.class);
    }

    public static com.google.protobuf.Parser<HPAccountBoundConfirm> PARSER =
        new com.google.protobuf.AbstractParser<HPAccountBoundConfirm>() {
      public HPAccountBoundConfirm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPAccountBoundConfirm(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPAccountBoundConfirm> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string wallet = 2;
    public static final int WALLET_FIELD_NUMBER = 2;
    private java.lang.Object wallet_;
    /**
     * <code>required string wallet = 2;</code>
     */
    public boolean hasWallet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string wallet = 2;</code>
     */
    public java.lang.String getWallet() {
      java.lang.Object ref = wallet_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wallet_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string wallet = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWalletBytes() {
      java.lang.Object ref = wallet_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wallet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = "";
      wallet_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWallet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getWalletBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getWalletBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPAccountBoundConfirm}
     *
     * <pre>
     * 领取帐号绑定奖励
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.class, com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.Builder.class);
      }

      // Construct using com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        wallet_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirm_descriptor;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm getDefaultInstanceForType() {
        return com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.getDefaultInstance();
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm build() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm buildPartial() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm result = new com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.wallet_ = wallet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm) {
          return mergeFrom((com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm other) {
        if (other == com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasWallet()) {
          bitField0_ |= 0x00000002;
          wallet_ = other.wallet_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasWallet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.AccountBound.HPAccountBoundConfirm) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userId = 1;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      // required string wallet = 2;
      private java.lang.Object wallet_ = "";
      /**
       * <code>required string wallet = 2;</code>
       */
      public boolean hasWallet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string wallet = 2;</code>
       */
      public java.lang.String getWallet() {
        java.lang.Object ref = wallet_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wallet_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string wallet = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWalletBytes() {
        java.lang.Object ref = wallet_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wallet_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string wallet = 2;</code>
       */
      public Builder setWallet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        wallet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string wallet = 2;</code>
       */
      public Builder clearWallet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        wallet_ = getDefaultInstance().getWallet();
        onChanged();
        return this;
      }
      /**
       * <code>required string wallet = 2;</code>
       */
      public Builder setWalletBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        wallet_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPAccountBoundConfirm)
    }

    static {
      defaultInstance = new HPAccountBoundConfirm(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPAccountBoundConfirm)
  }

  public interface HPAccountBoundConfirmRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 accountStatus = 1;
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    boolean hasAccountStatus();
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    int getAccountStatus();

    // required int32 accountReward = 2;
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    boolean hasAccountReward();
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    int getAccountReward();
  }
  /**
   * Protobuf type {@code HPAccountBoundConfirmRet}
   */
  public static final class HPAccountBoundConfirmRet extends
      com.google.protobuf.GeneratedMessage
      implements HPAccountBoundConfirmRetOrBuilder {
    // Use HPAccountBoundConfirmRet.newBuilder() to construct.
    private HPAccountBoundConfirmRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPAccountBoundConfirmRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPAccountBoundConfirmRet defaultInstance;
    public static HPAccountBoundConfirmRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPAccountBoundConfirmRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPAccountBoundConfirmRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountStatus_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountReward_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirmRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirmRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.class, com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPAccountBoundConfirmRet> PARSER =
        new com.google.protobuf.AbstractParser<HPAccountBoundConfirmRet>() {
      public HPAccountBoundConfirmRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPAccountBoundConfirmRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPAccountBoundConfirmRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 accountStatus = 1;
    public static final int ACCOUNTSTATUS_FIELD_NUMBER = 1;
    private int accountStatus_;
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    public boolean hasAccountStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 accountStatus = 1;</code>
     *
     * <pre>
     * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
     * </pre>
     */
    public int getAccountStatus() {
      return accountStatus_;
    }

    // required int32 accountReward = 2;
    public static final int ACCOUNTREWARD_FIELD_NUMBER = 2;
    private int accountReward_;
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    public boolean hasAccountReward() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 accountReward = 2;</code>
     */
    public int getAccountReward() {
      return accountReward_;
    }

    private void initFields() {
      accountStatus_ = 0;
      accountReward_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, accountStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountReward_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, accountStatus_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPAccountBoundConfirmRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirmRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirmRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.class, com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountReward_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.AccountBound.internal_static_HPAccountBoundConfirmRet_descriptor;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet build() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet buildPartial() {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet result = new com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountStatus_ = accountStatus_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountReward_ = accountReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet) {
          return mergeFrom((com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet other) {
        if (other == com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet.getDefaultInstance()) return this;
        if (other.hasAccountStatus()) {
          setAccountStatus(other.getAccountStatus());
        }
        if (other.hasAccountReward()) {
          setAccountReward(other.getAccountReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountStatus()) {
          
          return false;
        }
        if (!hasAccountReward()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.AccountBound.HPAccountBoundConfirmRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 accountStatus = 1;
      private int accountStatus_ ;
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public boolean hasAccountStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public int getAccountStatus() {
        return accountStatus_;
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public Builder setAccountStatus(int value) {
        bitField0_ |= 0x00000001;
        accountStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountStatus = 1;</code>
       *
       * <pre>
       * 帐号状态(1: 未绑定帐号 2: 绑定帐号,未领取 3: 绑定帐号,已领取)
       * </pre>
       */
      public Builder clearAccountStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountStatus_ = 0;
        onChanged();
        return this;
      }

      // required int32 accountReward = 2;
      private int accountReward_ ;
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public boolean hasAccountReward() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public int getAccountReward() {
        return accountReward_;
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public Builder setAccountReward(int value) {
        bitField0_ |= 0x00000002;
        accountReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountReward = 2;</code>
       */
      public Builder clearAccountReward() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountReward_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPAccountBoundConfirmRet)
    }

    static {
      defaultInstance = new HPAccountBoundConfirmRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPAccountBoundConfirmRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPAccountBoundInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPAccountBoundInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPAccountBoundRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPAccountBoundRet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPAccountBoundConfirm_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPAccountBoundConfirm_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPAccountBoundConfirmRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPAccountBoundConfirmRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AccountBound.proto\"\024\n\022HPAccountBoundIn" +
      "fo\"A\n\021HPAccountBoundRet\022\025\n\raccountStatus" +
      "\030\001 \002(\005\022\025\n\raccountReward\030\002 \002(\005\"7\n\025HPAccou" +
      "ntBoundConfirm\022\016\n\006userId\030\001 \002(\t\022\016\n\006wallet" +
      "\030\002 \002(\t\"H\n\030HPAccountBoundConfirmRet\022\025\n\rac" +
      "countStatus\030\001 \002(\005\022\025\n\raccountReward\030\002 \002(\005" +
      "B\031\n\027com.guaji.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPAccountBoundInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPAccountBoundInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPAccountBoundInfo_descriptor,
              new java.lang.String[] { });
          internal_static_HPAccountBoundRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPAccountBoundRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPAccountBoundRet_descriptor,
              new java.lang.String[] { "AccountStatus", "AccountReward", });
          internal_static_HPAccountBoundConfirm_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HPAccountBoundConfirm_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPAccountBoundConfirm_descriptor,
              new java.lang.String[] { "UserId", "Wallet", });
          internal_static_HPAccountBoundConfirmRet_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_HPAccountBoundConfirmRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPAccountBoundConfirmRet_descriptor,
              new java.lang.String[] { "AccountStatus", "AccountReward", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
