// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrystalShop.proto

package com.guaji.game.protocol;

public final class CrystalShop {
  private CrystalShop() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CrystalShopItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required int32 itemType = 2;
    /**
     * <code>required int32 itemType = 2;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    boolean hasItemType();
    /**
     * <code>required int32 itemType = 2;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    int getItemType();

    // required int32 itemId = 3;
    /**
     * <code>required int32 itemId = 3;</code>
     *
     * <pre>
     *道具id
     * </pre>
     */
    boolean hasItemId();
    /**
     * <code>required int32 itemId = 3;</code>
     *
     * <pre>
     *道具id
     * </pre>
     */
    int getItemId();

    // required int32 itemCount = 4;
    /**
     * <code>required int32 itemCount = 4;</code>
     *
     * <pre>
     *道具数量
     * </pre>
     */
    boolean hasItemCount();
    /**
     * <code>required int32 itemCount = 4;</code>
     *
     * <pre>
     *道具数量
     * </pre>
     */
    int getItemCount();

    // required int32 costCount = 5;
    /**
     * <code>required int32 costCount = 5;</code>
     *
     * <pre>
     *需要消耗数量
     * </pre>
     */
    boolean hasCostCount();
    /**
     * <code>required int32 costCount = 5;</code>
     *
     * <pre>
     *需要消耗数量
     * </pre>
     */
    int getCostCount();

    // required int32 costType = 6;
    /**
     * <code>required int32 costType = 6;</code>
     *
     * <pre>
     *钻石1 水晶20
     * </pre>
     */
    boolean hasCostType();
    /**
     * <code>required int32 costType = 6;</code>
     *
     * <pre>
     *钻石1 水晶20
     * </pre>
     */
    int getCostType();
  }
  /**
   * Protobuf type {@code CrystalShopItem}
   */
  public static final class CrystalShopItem extends
      com.google.protobuf.GeneratedMessage
      implements CrystalShopItemOrBuilder {
    // Use CrystalShopItem.newBuilder() to construct.
    private CrystalShopItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CrystalShopItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CrystalShopItem defaultInstance;
    public static CrystalShopItem getDefaultInstance() {
      return defaultInstance;
    }

    public CrystalShopItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CrystalShopItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              itemType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              itemId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              itemCount_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              costCount_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              costType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.CrystalShop.internal_static_CrystalShopItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.CrystalShop.internal_static_CrystalShopItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.CrystalShop.CrystalShopItem.class, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder.class);
    }

    public static com.google.protobuf.Parser<CrystalShopItem> PARSER =
        new com.google.protobuf.AbstractParser<CrystalShopItem>() {
      public CrystalShopItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CrystalShopItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CrystalShopItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     *
     * <pre>
     *本商品id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 itemType = 2;
    public static final int ITEMTYPE_FIELD_NUMBER = 2;
    private int itemType_;
    /**
     * <code>required int32 itemType = 2;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    public boolean hasItemType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 itemType = 2;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    public int getItemType() {
      return itemType_;
    }

    // required int32 itemId = 3;
    public static final int ITEMID_FIELD_NUMBER = 3;
    private int itemId_;
    /**
     * <code>required int32 itemId = 3;</code>
     *
     * <pre>
     *道具id
     * </pre>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 itemId = 3;</code>
     *
     * <pre>
     *道具id
     * </pre>
     */
    public int getItemId() {
      return itemId_;
    }

    // required int32 itemCount = 4;
    public static final int ITEMCOUNT_FIELD_NUMBER = 4;
    private int itemCount_;
    /**
     * <code>required int32 itemCount = 4;</code>
     *
     * <pre>
     *道具数量
     * </pre>
     */
    public boolean hasItemCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 itemCount = 4;</code>
     *
     * <pre>
     *道具数量
     * </pre>
     */
    public int getItemCount() {
      return itemCount_;
    }

    // required int32 costCount = 5;
    public static final int COSTCOUNT_FIELD_NUMBER = 5;
    private int costCount_;
    /**
     * <code>required int32 costCount = 5;</code>
     *
     * <pre>
     *需要消耗数量
     * </pre>
     */
    public boolean hasCostCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 costCount = 5;</code>
     *
     * <pre>
     *需要消耗数量
     * </pre>
     */
    public int getCostCount() {
      return costCount_;
    }

    // required int32 costType = 6;
    public static final int COSTTYPE_FIELD_NUMBER = 6;
    private int costType_;
    /**
     * <code>required int32 costType = 6;</code>
     *
     * <pre>
     *钻石1 水晶20
     * </pre>
     */
    public boolean hasCostType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 costType = 6;</code>
     *
     * <pre>
     *钻石1 水晶20
     * </pre>
     */
    public int getCostType() {
      return costType_;
    }

    private void initFields() {
      id_ = "";
      itemType_ = 0;
      itemId_ = 0;
      itemCount_ = 0;
      costCount_ = 0;
      costType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCostCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCostType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, itemType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, itemId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, itemCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, costCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, costType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, itemId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, itemCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, costCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, costType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.CrystalShopItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.CrystalShop.CrystalShopItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CrystalShopItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.CrystalShop.internal_static_CrystalShopItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.CrystalShop.internal_static_CrystalShopItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.CrystalShop.CrystalShopItem.class, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder.class);
      }

      // Construct using com.guaji.game.protocol.CrystalShop.CrystalShopItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        itemType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        itemCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        costCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        costType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.CrystalShop.internal_static_CrystalShopItem_descriptor;
      }

      public com.guaji.game.protocol.CrystalShop.CrystalShopItem getDefaultInstanceForType() {
        return com.guaji.game.protocol.CrystalShop.CrystalShopItem.getDefaultInstance();
      }

      public com.guaji.game.protocol.CrystalShop.CrystalShopItem build() {
        com.guaji.game.protocol.CrystalShop.CrystalShopItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.CrystalShop.CrystalShopItem buildPartial() {
        com.guaji.game.protocol.CrystalShop.CrystalShopItem result = new com.guaji.game.protocol.CrystalShop.CrystalShopItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemType_ = itemType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.itemCount_ = itemCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.costCount_ = costCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.costType_ = costType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.CrystalShop.CrystalShopItem) {
          return mergeFrom((com.guaji.game.protocol.CrystalShop.CrystalShopItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.CrystalShop.CrystalShopItem other) {
        if (other == com.guaji.game.protocol.CrystalShop.CrystalShopItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasItemType()) {
          setItemType(other.getItemType());
        }
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasItemCount()) {
          setItemCount(other.getItemCount());
        }
        if (other.hasCostCount()) {
          setCostCount(other.getCostCount());
        }
        if (other.hasCostType()) {
          setCostType(other.getCostType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasItemType()) {
          
          return false;
        }
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasItemCount()) {
          
          return false;
        }
        if (!hasCostCount()) {
          
          return false;
        }
        if (!hasCostType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.CrystalShop.CrystalShopItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.CrystalShop.CrystalShopItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       *
       * <pre>
       *本商品id
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required int32 itemType = 2;
      private int itemType_ ;
      /**
       * <code>required int32 itemType = 2;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public boolean hasItemType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 itemType = 2;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public int getItemType() {
        return itemType_;
      }
      /**
       * <code>required int32 itemType = 2;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public Builder setItemType(int value) {
        bitField0_ |= 0x00000002;
        itemType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemType = 2;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public Builder clearItemType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemType_ = 0;
        onChanged();
        return this;
      }

      // required int32 itemId = 3;
      private int itemId_ ;
      /**
       * <code>required int32 itemId = 3;</code>
       *
       * <pre>
       *道具id
       * </pre>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 itemId = 3;</code>
       *
       * <pre>
       *道具id
       * </pre>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>required int32 itemId = 3;</code>
       *
       * <pre>
       *道具id
       * </pre>
       */
      public Builder setItemId(int value) {
        bitField0_ |= 0x00000004;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemId = 3;</code>
       *
       * <pre>
       *道具id
       * </pre>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        itemId_ = 0;
        onChanged();
        return this;
      }

      // required int32 itemCount = 4;
      private int itemCount_ ;
      /**
       * <code>required int32 itemCount = 4;</code>
       *
       * <pre>
       *道具数量
       * </pre>
       */
      public boolean hasItemCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 itemCount = 4;</code>
       *
       * <pre>
       *道具数量
       * </pre>
       */
      public int getItemCount() {
        return itemCount_;
      }
      /**
       * <code>required int32 itemCount = 4;</code>
       *
       * <pre>
       *道具数量
       * </pre>
       */
      public Builder setItemCount(int value) {
        bitField0_ |= 0x00000008;
        itemCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemCount = 4;</code>
       *
       * <pre>
       *道具数量
       * </pre>
       */
      public Builder clearItemCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        itemCount_ = 0;
        onChanged();
        return this;
      }

      // required int32 costCount = 5;
      private int costCount_ ;
      /**
       * <code>required int32 costCount = 5;</code>
       *
       * <pre>
       *需要消耗数量
       * </pre>
       */
      public boolean hasCostCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 costCount = 5;</code>
       *
       * <pre>
       *需要消耗数量
       * </pre>
       */
      public int getCostCount() {
        return costCount_;
      }
      /**
       * <code>required int32 costCount = 5;</code>
       *
       * <pre>
       *需要消耗数量
       * </pre>
       */
      public Builder setCostCount(int value) {
        bitField0_ |= 0x00000010;
        costCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 costCount = 5;</code>
       *
       * <pre>
       *需要消耗数量
       * </pre>
       */
      public Builder clearCostCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        costCount_ = 0;
        onChanged();
        return this;
      }

      // required int32 costType = 6;
      private int costType_ ;
      /**
       * <code>required int32 costType = 6;</code>
       *
       * <pre>
       *钻石1 水晶20
       * </pre>
       */
      public boolean hasCostType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 costType = 6;</code>
       *
       * <pre>
       *钻石1 水晶20
       * </pre>
       */
      public int getCostType() {
        return costType_;
      }
      /**
       * <code>required int32 costType = 6;</code>
       *
       * <pre>
       *钻石1 水晶20
       * </pre>
       */
      public Builder setCostType(int value) {
        bitField0_ |= 0x00000020;
        costType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 costType = 6;</code>
       *
       * <pre>
       *钻石1 水晶20
       * </pre>
       */
      public Builder clearCostType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        costType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CrystalShopItem)
    }

    static {
      defaultInstance = new CrystalShopItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CrystalShopItem)
  }

  public interface HPCrystalShopListRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .CrystalShopItem shopItems = 1;
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem> 
        getShopItemsList();
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    com.guaji.game.protocol.CrystalShop.CrystalShopItem getShopItems(int index);
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    int getShopItemsCount();
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    java.util.List<? extends com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder> 
        getShopItemsOrBuilderList();
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder getShopItemsOrBuilder(
        int index);

    // required int32 refreshCostCrystal = 2;
    /**
     * <code>required int32 refreshCostCrystal = 2;</code>
     */
    boolean hasRefreshCostCrystal();
    /**
     * <code>required int32 refreshCostCrystal = 2;</code>
     */
    int getRefreshCostCrystal();
  }
  /**
   * Protobuf type {@code HPCrystalShopListRet}
   */
  public static final class HPCrystalShopListRet extends
      com.google.protobuf.GeneratedMessage
      implements HPCrystalShopListRetOrBuilder {
    // Use HPCrystalShopListRet.newBuilder() to construct.
    private HPCrystalShopListRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPCrystalShopListRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPCrystalShopListRet defaultInstance;
    public static HPCrystalShopListRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPCrystalShopListRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPCrystalShopListRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                shopItems_ = new java.util.ArrayList<com.guaji.game.protocol.CrystalShop.CrystalShopItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              shopItems_.add(input.readMessage(com.guaji.game.protocol.CrystalShop.CrystalShopItem.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              refreshCostCrystal_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          shopItems_ = java.util.Collections.unmodifiableList(shopItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalShopListRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalShopListRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.class, com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPCrystalShopListRet> PARSER =
        new com.google.protobuf.AbstractParser<HPCrystalShopListRet>() {
      public HPCrystalShopListRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPCrystalShopListRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPCrystalShopListRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .CrystalShopItem shopItems = 1;
    public static final int SHOPITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem> shopItems_;
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    public java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem> getShopItemsList() {
      return shopItems_;
    }
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    public java.util.List<? extends com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder> 
        getShopItemsOrBuilderList() {
      return shopItems_;
    }
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    public int getShopItemsCount() {
      return shopItems_.size();
    }
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    public com.guaji.game.protocol.CrystalShop.CrystalShopItem getShopItems(int index) {
      return shopItems_.get(index);
    }
    /**
     * <code>repeated .CrystalShopItem shopItems = 1;</code>
     */
    public com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder getShopItemsOrBuilder(
        int index) {
      return shopItems_.get(index);
    }

    // required int32 refreshCostCrystal = 2;
    public static final int REFRESHCOSTCRYSTAL_FIELD_NUMBER = 2;
    private int refreshCostCrystal_;
    /**
     * <code>required int32 refreshCostCrystal = 2;</code>
     */
    public boolean hasRefreshCostCrystal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 refreshCostCrystal = 2;</code>
     */
    public int getRefreshCostCrystal() {
      return refreshCostCrystal_;
    }

    private void initFields() {
      shopItems_ = java.util.Collections.emptyList();
      refreshCostCrystal_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRefreshCostCrystal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getShopItemsCount(); i++) {
        if (!getShopItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < shopItems_.size(); i++) {
        output.writeMessage(1, shopItems_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, refreshCostCrystal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < shopItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, shopItems_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, refreshCostCrystal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPCrystalShopListRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.CrystalShop.HPCrystalShopListRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalShopListRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalShopListRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.class, com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getShopItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (shopItemsBuilder_ == null) {
          shopItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          shopItemsBuilder_.clear();
        }
        refreshCostCrystal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalShopListRet_descriptor;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet build() {
        com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet buildPartial() {
        com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet result = new com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (shopItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            shopItems_ = java.util.Collections.unmodifiableList(shopItems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.shopItems_ = shopItems_;
        } else {
          result.shopItems_ = shopItemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.refreshCostCrystal_ = refreshCostCrystal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet) {
          return mergeFrom((com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet other) {
        if (other == com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet.getDefaultInstance()) return this;
        if (shopItemsBuilder_ == null) {
          if (!other.shopItems_.isEmpty()) {
            if (shopItems_.isEmpty()) {
              shopItems_ = other.shopItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureShopItemsIsMutable();
              shopItems_.addAll(other.shopItems_);
            }
            onChanged();
          }
        } else {
          if (!other.shopItems_.isEmpty()) {
            if (shopItemsBuilder_.isEmpty()) {
              shopItemsBuilder_.dispose();
              shopItemsBuilder_ = null;
              shopItems_ = other.shopItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              shopItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getShopItemsFieldBuilder() : null;
            } else {
              shopItemsBuilder_.addAllMessages(other.shopItems_);
            }
          }
        }
        if (other.hasRefreshCostCrystal()) {
          setRefreshCostCrystal(other.getRefreshCostCrystal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRefreshCostCrystal()) {
          
          return false;
        }
        for (int i = 0; i < getShopItemsCount(); i++) {
          if (!getShopItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.CrystalShop.HPCrystalShopListRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .CrystalShopItem shopItems = 1;
      private java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem> shopItems_ =
        java.util.Collections.emptyList();
      private void ensureShopItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          shopItems_ = new java.util.ArrayList<com.guaji.game.protocol.CrystalShop.CrystalShopItem>(shopItems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.guaji.game.protocol.CrystalShop.CrystalShopItem, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder, com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder> shopItemsBuilder_;

      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem> getShopItemsList() {
        if (shopItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shopItems_);
        } else {
          return shopItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public int getShopItemsCount() {
        if (shopItemsBuilder_ == null) {
          return shopItems_.size();
        } else {
          return shopItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public com.guaji.game.protocol.CrystalShop.CrystalShopItem getShopItems(int index) {
        if (shopItemsBuilder_ == null) {
          return shopItems_.get(index);
        } else {
          return shopItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder setShopItems(
          int index, com.guaji.game.protocol.CrystalShop.CrystalShopItem value) {
        if (shopItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopItemsIsMutable();
          shopItems_.set(index, value);
          onChanged();
        } else {
          shopItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder setShopItems(
          int index, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder builderForValue) {
        if (shopItemsBuilder_ == null) {
          ensureShopItemsIsMutable();
          shopItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          shopItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder addShopItems(com.guaji.game.protocol.CrystalShop.CrystalShopItem value) {
        if (shopItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopItemsIsMutable();
          shopItems_.add(value);
          onChanged();
        } else {
          shopItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder addShopItems(
          int index, com.guaji.game.protocol.CrystalShop.CrystalShopItem value) {
        if (shopItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopItemsIsMutable();
          shopItems_.add(index, value);
          onChanged();
        } else {
          shopItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder addShopItems(
          com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder builderForValue) {
        if (shopItemsBuilder_ == null) {
          ensureShopItemsIsMutable();
          shopItems_.add(builderForValue.build());
          onChanged();
        } else {
          shopItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder addShopItems(
          int index, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder builderForValue) {
        if (shopItemsBuilder_ == null) {
          ensureShopItemsIsMutable();
          shopItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          shopItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder addAllShopItems(
          java.lang.Iterable<? extends com.guaji.game.protocol.CrystalShop.CrystalShopItem> values) {
        if (shopItemsBuilder_ == null) {
          ensureShopItemsIsMutable();
          super.addAll(values, shopItems_);
          onChanged();
        } else {
          shopItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder clearShopItems() {
        if (shopItemsBuilder_ == null) {
          shopItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          shopItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public Builder removeShopItems(int index) {
        if (shopItemsBuilder_ == null) {
          ensureShopItemsIsMutable();
          shopItems_.remove(index);
          onChanged();
        } else {
          shopItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder getShopItemsBuilder(
          int index) {
        return getShopItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder getShopItemsOrBuilder(
          int index) {
        if (shopItemsBuilder_ == null) {
          return shopItems_.get(index);  } else {
          return shopItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public java.util.List<? extends com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder> 
           getShopItemsOrBuilderList() {
        if (shopItemsBuilder_ != null) {
          return shopItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shopItems_);
        }
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder addShopItemsBuilder() {
        return getShopItemsFieldBuilder().addBuilder(
            com.guaji.game.protocol.CrystalShop.CrystalShopItem.getDefaultInstance());
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder addShopItemsBuilder(
          int index) {
        return getShopItemsFieldBuilder().addBuilder(
            index, com.guaji.game.protocol.CrystalShop.CrystalShopItem.getDefaultInstance());
      }
      /**
       * <code>repeated .CrystalShopItem shopItems = 1;</code>
       */
      public java.util.List<com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder> 
           getShopItemsBuilderList() {
        return getShopItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.guaji.game.protocol.CrystalShop.CrystalShopItem, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder, com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder> 
          getShopItemsFieldBuilder() {
        if (shopItemsBuilder_ == null) {
          shopItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.guaji.game.protocol.CrystalShop.CrystalShopItem, com.guaji.game.protocol.CrystalShop.CrystalShopItem.Builder, com.guaji.game.protocol.CrystalShop.CrystalShopItemOrBuilder>(
                  shopItems_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          shopItems_ = null;
        }
        return shopItemsBuilder_;
      }

      // required int32 refreshCostCrystal = 2;
      private int refreshCostCrystal_ ;
      /**
       * <code>required int32 refreshCostCrystal = 2;</code>
       */
      public boolean hasRefreshCostCrystal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 refreshCostCrystal = 2;</code>
       */
      public int getRefreshCostCrystal() {
        return refreshCostCrystal_;
      }
      /**
       * <code>required int32 refreshCostCrystal = 2;</code>
       */
      public Builder setRefreshCostCrystal(int value) {
        bitField0_ |= 0x00000002;
        refreshCostCrystal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 refreshCostCrystal = 2;</code>
       */
      public Builder clearRefreshCostCrystal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        refreshCostCrystal_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPCrystalShopListRet)
    }

    static {
      defaultInstance = new HPCrystalShopListRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPCrystalShopListRet)
  }

  public interface HPCrystalBuyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code HPCrystalBuy}
   */
  public static final class HPCrystalBuy extends
      com.google.protobuf.GeneratedMessage
      implements HPCrystalBuyOrBuilder {
    // Use HPCrystalBuy.newBuilder() to construct.
    private HPCrystalBuy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPCrystalBuy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPCrystalBuy defaultInstance;
    public static HPCrystalBuy getDefaultInstance() {
      return defaultInstance;
    }

    public HPCrystalBuy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPCrystalBuy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.CrystalShop.HPCrystalBuy.class, com.guaji.game.protocol.CrystalShop.HPCrystalBuy.Builder.class);
    }

    public static com.google.protobuf.Parser<HPCrystalBuy> PARSER =
        new com.google.protobuf.AbstractParser<HPCrystalBuy>() {
      public HPCrystalBuy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPCrystalBuy(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPCrystalBuy> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.CrystalShop.HPCrystalBuy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPCrystalBuy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.CrystalShop.HPCrystalBuyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.CrystalShop.HPCrystalBuy.class, com.guaji.game.protocol.CrystalShop.HPCrystalBuy.Builder.class);
      }

      // Construct using com.guaji.game.protocol.CrystalShop.HPCrystalBuy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuy_descriptor;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuy getDefaultInstanceForType() {
        return com.guaji.game.protocol.CrystalShop.HPCrystalBuy.getDefaultInstance();
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuy build() {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuy buildPartial() {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuy result = new com.guaji.game.protocol.CrystalShop.HPCrystalBuy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.CrystalShop.HPCrystalBuy) {
          return mergeFrom((com.guaji.game.protocol.CrystalShop.HPCrystalBuy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.CrystalShop.HPCrystalBuy other) {
        if (other == com.guaji.game.protocol.CrystalShop.HPCrystalBuy.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.CrystalShop.HPCrystalBuy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPCrystalBuy)
    }

    static {
      defaultInstance = new HPCrystalBuy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPCrystalBuy)
  }

  public interface HPCrystalBuyRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code HPCrystalBuyRet}
   */
  public static final class HPCrystalBuyRet extends
      com.google.protobuf.GeneratedMessage
      implements HPCrystalBuyRetOrBuilder {
    // Use HPCrystalBuyRet.newBuilder() to construct.
    private HPCrystalBuyRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPCrystalBuyRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPCrystalBuyRet defaultInstance;
    public static HPCrystalBuyRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPCrystalBuyRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPCrystalBuyRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuyRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuyRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.class, com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPCrystalBuyRet> PARSER =
        new com.google.protobuf.AbstractParser<HPCrystalBuyRet>() {
      public HPCrystalBuyRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPCrystalBuyRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPCrystalBuyRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPCrystalBuyRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.CrystalShop.HPCrystalBuyRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuyRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuyRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.class, com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.CrystalShop.internal_static_HPCrystalBuyRet_descriptor;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet build() {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet buildPartial() {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet result = new com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet) {
          return mergeFrom((com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet other) {
        if (other == com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.CrystalShop.HPCrystalBuyRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPCrystalBuyRet)
    }

    static {
      defaultInstance = new HPCrystalBuyRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPCrystalBuyRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrystalShopItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrystalShopItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPCrystalShopListRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPCrystalShopListRet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPCrystalBuy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPCrystalBuy_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPCrystalBuyRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPCrystalBuyRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CrystalShop.proto\"w\n\017CrystalShopItem\022\n" +
      "\n\002id\030\001 \002(\t\022\020\n\010itemType\030\002 \002(\005\022\016\n\006itemId\030\003" +
      " \002(\005\022\021\n\titemCount\030\004 \002(\005\022\021\n\tcostCount\030\005 \002" +
      "(\005\022\020\n\010costType\030\006 \002(\005\"W\n\024HPCrystalShopLis" +
      "tRet\022#\n\tshopItems\030\001 \003(\0132\020.CrystalShopIte" +
      "m\022\032\n\022refreshCostCrystal\030\002 \002(\005\"\032\n\014HPCryst" +
      "alBuy\022\n\n\002id\030\001 \002(\t\"\035\n\017HPCrystalBuyRet\022\n\n\002" +
      "id\030\001 \002(\tB\031\n\027com.guaji.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CrystalShopItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CrystalShopItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CrystalShopItem_descriptor,
              new java.lang.String[] { "Id", "ItemType", "ItemId", "ItemCount", "CostCount", "CostType", });
          internal_static_HPCrystalShopListRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPCrystalShopListRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPCrystalShopListRet_descriptor,
              new java.lang.String[] { "ShopItems", "RefreshCostCrystal", });
          internal_static_HPCrystalBuy_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HPCrystalBuy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPCrystalBuy_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_HPCrystalBuyRet_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_HPCrystalBuyRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPCrystalBuyRet_descriptor,
              new java.lang.String[] { "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
