// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

package com.guaji.game.protocol;

public final class Item {
  private Item() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required int32 itemId = 2;
    /**
     * <code>required int32 itemId = 2;</code>
     */
    boolean hasItemId();
    /**
     * <code>required int32 itemId = 2;</code>
     */
    int getItemId();

    // required int64 count = 3;
    /**
     * <code>required int64 count = 3;</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 3;</code>
     */
    long getCount();

    // required int32 status = 4;
    /**
     * <code>required int32 status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 4;</code>
     */
    int getStatus();

    // optional int32 exp = 5;
    /**
     * <code>optional int32 exp = 5;</code>
     *
     * <pre>
     *如果是宝石，给一个强化经验
     * </pre>
     */
    boolean hasExp();
    /**
     * <code>optional int32 exp = 5;</code>
     *
     * <pre>
     *如果是宝石，给一个强化经验
     * </pre>
     */
    int getExp();
  }
  /**
   * Protobuf type {@code ItemInfo}
   */
  public static final class ItemInfo extends
      com.google.protobuf.GeneratedMessage
      implements ItemInfoOrBuilder {
    // Use ItemInfo.newBuilder() to construct.
    private ItemInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemInfo defaultInstance;
    public static ItemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ItemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              itemId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              count_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              status_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              exp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.Item.internal_static_ItemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.Item.internal_static_ItemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.Item.ItemInfo.class, com.guaji.game.protocol.Item.ItemInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemInfo> PARSER =
        new com.google.protobuf.AbstractParser<ItemInfo>() {
      public ItemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required int32 itemId = 2;
    public static final int ITEMID_FIELD_NUMBER = 2;
    private int itemId_;
    /**
     * <code>required int32 itemId = 2;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 itemId = 2;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    // required int64 count = 3;
    public static final int COUNT_FIELD_NUMBER = 3;
    private long count_;
    /**
     * <code>required int64 count = 3;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 count = 3;</code>
     */
    public long getCount() {
      return count_;
    }

    // required int32 status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>required int32 status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    // optional int32 exp = 5;
    public static final int EXP_FIELD_NUMBER = 5;
    private int exp_;
    /**
     * <code>optional int32 exp = 5;</code>
     *
     * <pre>
     *如果是宝石，给一个强化经验
     * </pre>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 exp = 5;</code>
     *
     * <pre>
     *如果是宝石，给一个强化经验
     * </pre>
     */
    public int getExp() {
      return exp_;
    }

    private void initFields() {
      id_ = 0;
      itemId_ = 0;
      count_ = 0L;
      status_ = 0;
      exp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, count_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, exp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, count_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, exp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.Item.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.Item.ItemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.Item.ItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.Item.internal_static_ItemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.Item.internal_static_ItemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.Item.ItemInfo.class, com.guaji.game.protocol.Item.ItemInfo.Builder.class);
      }

      // Construct using com.guaji.game.protocol.Item.ItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.Item.internal_static_ItemInfo_descriptor;
      }

      public com.guaji.game.protocol.Item.ItemInfo getDefaultInstanceForType() {
        return com.guaji.game.protocol.Item.ItemInfo.getDefaultInstance();
      }

      public com.guaji.game.protocol.Item.ItemInfo build() {
        com.guaji.game.protocol.Item.ItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.Item.ItemInfo buildPartial() {
        com.guaji.game.protocol.Item.ItemInfo result = new com.guaji.game.protocol.Item.ItemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exp_ = exp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.Item.ItemInfo) {
          return mergeFrom((com.guaji.game.protocol.Item.ItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.Item.ItemInfo other) {
        if (other == com.guaji.game.protocol.Item.ItemInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.Item.ItemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.Item.ItemInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required int32 itemId = 2;
      private int itemId_ ;
      /**
       * <code>required int32 itemId = 2;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 itemId = 2;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>required int32 itemId = 2;</code>
       */
      public Builder setItemId(int value) {
        bitField0_ |= 0x00000002;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemId = 2;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = 0;
        onChanged();
        return this;
      }

      // required int64 count = 3;
      private long count_ ;
      /**
       * <code>required int64 count = 3;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 count = 3;</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 3;</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000004;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 3;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0L;
        onChanged();
        return this;
      }

      // required int32 status = 4;
      private int status_ ;
      /**
       * <code>required int32 status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional int32 exp = 5;
      private int exp_ ;
      /**
       * <code>optional int32 exp = 5;</code>
       *
       * <pre>
       *如果是宝石，给一个强化经验
       * </pre>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 exp = 5;</code>
       *
       * <pre>
       *如果是宝石，给一个强化经验
       * </pre>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       *
       * <pre>
       *如果是宝石，给一个强化经验
       * </pre>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000010;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       *
       * <pre>
       *如果是宝石，给一个强化经验
       * </pre>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exp_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemInfo)
    }

    static {
      defaultInstance = new ItemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemInfo)
  }

  public interface HPItemInfoSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ItemInfo itemInfos = 1;
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    java.util.List<com.guaji.game.protocol.Item.ItemInfo> 
        getItemInfosList();
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    com.guaji.game.protocol.Item.ItemInfo getItemInfos(int index);
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    int getItemInfosCount();
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    java.util.List<? extends com.guaji.game.protocol.Item.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList();
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    com.guaji.game.protocol.Item.ItemInfoOrBuilder getItemInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HPItemInfoSync}
   */
  public static final class HPItemInfoSync extends
      com.google.protobuf.GeneratedMessage
      implements HPItemInfoSyncOrBuilder {
    // Use HPItemInfoSync.newBuilder() to construct.
    private HPItemInfoSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPItemInfoSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPItemInfoSync defaultInstance;
    public static HPItemInfoSync getDefaultInstance() {
      return defaultInstance;
    }

    public HPItemInfoSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPItemInfoSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemInfos_ = new java.util.ArrayList<com.guaji.game.protocol.Item.ItemInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemInfos_.add(input.readMessage(com.guaji.game.protocol.Item.ItemInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.Item.internal_static_HPItemInfoSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.Item.internal_static_HPItemInfoSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.Item.HPItemInfoSync.class, com.guaji.game.protocol.Item.HPItemInfoSync.Builder.class);
    }

    public static com.google.protobuf.Parser<HPItemInfoSync> PARSER =
        new com.google.protobuf.AbstractParser<HPItemInfoSync>() {
      public HPItemInfoSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPItemInfoSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPItemInfoSync> getParserForType() {
      return PARSER;
    }

    // repeated .ItemInfo itemInfos = 1;
    public static final int ITEMINFOS_FIELD_NUMBER = 1;
    private java.util.List<com.guaji.game.protocol.Item.ItemInfo> itemInfos_;
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    public java.util.List<com.guaji.game.protocol.Item.ItemInfo> getItemInfosList() {
      return itemInfos_;
    }
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    public java.util.List<? extends com.guaji.game.protocol.Item.ItemInfoOrBuilder> 
        getItemInfosOrBuilderList() {
      return itemInfos_;
    }
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    public int getItemInfosCount() {
      return itemInfos_.size();
    }
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    public com.guaji.game.protocol.Item.ItemInfo getItemInfos(int index) {
      return itemInfos_.get(index);
    }
    /**
     * <code>repeated .ItemInfo itemInfos = 1;</code>
     */
    public com.guaji.game.protocol.Item.ItemInfoOrBuilder getItemInfosOrBuilder(
        int index) {
      return itemInfos_.get(index);
    }

    private void initFields() {
      itemInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getItemInfosCount(); i++) {
        if (!getItemInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < itemInfos_.size(); i++) {
        output.writeMessage(1, itemInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < itemInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, itemInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.Item.HPItemInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.Item.HPItemInfoSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPItemInfoSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.Item.HPItemInfoSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.Item.internal_static_HPItemInfoSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.Item.internal_static_HPItemInfoSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.Item.HPItemInfoSync.class, com.guaji.game.protocol.Item.HPItemInfoSync.Builder.class);
      }

      // Construct using com.guaji.game.protocol.Item.HPItemInfoSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.Item.internal_static_HPItemInfoSync_descriptor;
      }

      public com.guaji.game.protocol.Item.HPItemInfoSync getDefaultInstanceForType() {
        return com.guaji.game.protocol.Item.HPItemInfoSync.getDefaultInstance();
      }

      public com.guaji.game.protocol.Item.HPItemInfoSync build() {
        com.guaji.game.protocol.Item.HPItemInfoSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.Item.HPItemInfoSync buildPartial() {
        com.guaji.game.protocol.Item.HPItemInfoSync result = new com.guaji.game.protocol.Item.HPItemInfoSync(this);
        int from_bitField0_ = bitField0_;
        if (itemInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            itemInfos_ = java.util.Collections.unmodifiableList(itemInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.itemInfos_ = itemInfos_;
        } else {
          result.itemInfos_ = itemInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.Item.HPItemInfoSync) {
          return mergeFrom((com.guaji.game.protocol.Item.HPItemInfoSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.Item.HPItemInfoSync other) {
        if (other == com.guaji.game.protocol.Item.HPItemInfoSync.getDefaultInstance()) return this;
        if (itemInfosBuilder_ == null) {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfos_.isEmpty()) {
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemInfosIsMutable();
              itemInfos_.addAll(other.itemInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.itemInfos_.isEmpty()) {
            if (itemInfosBuilder_.isEmpty()) {
              itemInfosBuilder_.dispose();
              itemInfosBuilder_ = null;
              itemInfos_ = other.itemInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemInfosFieldBuilder() : null;
            } else {
              itemInfosBuilder_.addAllMessages(other.itemInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemInfosCount(); i++) {
          if (!getItemInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.Item.HPItemInfoSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.Item.HPItemInfoSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ItemInfo itemInfos = 1;
      private java.util.List<com.guaji.game.protocol.Item.ItemInfo> itemInfos_ =
        java.util.Collections.emptyList();
      private void ensureItemInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemInfos_ = new java.util.ArrayList<com.guaji.game.protocol.Item.ItemInfo>(itemInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.guaji.game.protocol.Item.ItemInfo, com.guaji.game.protocol.Item.ItemInfo.Builder, com.guaji.game.protocol.Item.ItemInfoOrBuilder> itemInfosBuilder_;

      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<com.guaji.game.protocol.Item.ItemInfo> getItemInfosList() {
        if (itemInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemInfos_);
        } else {
          return itemInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public int getItemInfosCount() {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.size();
        } else {
          return itemInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public com.guaji.game.protocol.Item.ItemInfo getItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);
        } else {
          return itemInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder setItemInfos(
          int index, com.guaji.game.protocol.Item.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.set(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder setItemInfos(
          int index, com.guaji.game.protocol.Item.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(com.guaji.game.protocol.Item.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          int index, com.guaji.game.protocol.Item.ItemInfo value) {
        if (itemInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemInfosIsMutable();
          itemInfos_.add(index, value);
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          com.guaji.game.protocol.Item.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder addItemInfos(
          int index, com.guaji.game.protocol.Item.ItemInfo.Builder builderForValue) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder addAllItemInfos(
          java.lang.Iterable<? extends com.guaji.game.protocol.Item.ItemInfo> values) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          super.addAll(values, itemInfos_);
          onChanged();
        } else {
          itemInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder clearItemInfos() {
        if (itemInfosBuilder_ == null) {
          itemInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public Builder removeItemInfos(int index) {
        if (itemInfosBuilder_ == null) {
          ensureItemInfosIsMutable();
          itemInfos_.remove(index);
          onChanged();
        } else {
          itemInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public com.guaji.game.protocol.Item.ItemInfo.Builder getItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public com.guaji.game.protocol.Item.ItemInfoOrBuilder getItemInfosOrBuilder(
          int index) {
        if (itemInfosBuilder_ == null) {
          return itemInfos_.get(index);  } else {
          return itemInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<? extends com.guaji.game.protocol.Item.ItemInfoOrBuilder> 
           getItemInfosOrBuilderList() {
        if (itemInfosBuilder_ != null) {
          return itemInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemInfos_);
        }
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public com.guaji.game.protocol.Item.ItemInfo.Builder addItemInfosBuilder() {
        return getItemInfosFieldBuilder().addBuilder(
            com.guaji.game.protocol.Item.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public com.guaji.game.protocol.Item.ItemInfo.Builder addItemInfosBuilder(
          int index) {
        return getItemInfosFieldBuilder().addBuilder(
            index, com.guaji.game.protocol.Item.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemInfo itemInfos = 1;</code>
       */
      public java.util.List<com.guaji.game.protocol.Item.ItemInfo.Builder> 
           getItemInfosBuilderList() {
        return getItemInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.guaji.game.protocol.Item.ItemInfo, com.guaji.game.protocol.Item.ItemInfo.Builder, com.guaji.game.protocol.Item.ItemInfoOrBuilder> 
          getItemInfosFieldBuilder() {
        if (itemInfosBuilder_ == null) {
          itemInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.guaji.game.protocol.Item.ItemInfo, com.guaji.game.protocol.Item.ItemInfo.Builder, com.guaji.game.protocol.Item.ItemInfoOrBuilder>(
                  itemInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          itemInfos_ = null;
        }
        return itemInfosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HPItemInfoSync)
    }

    static {
      defaultInstance = new HPItemInfoSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPItemInfoSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPItemInfoSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPItemInfoSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nItem.proto\"R\n\010ItemInfo\022\n\n\002id\030\001 \002(\005\022\016\n\006" +
      "itemId\030\002 \002(\005\022\r\n\005count\030\003 \002(\003\022\016\n\006status\030\004 " +
      "\002(\005\022\013\n\003exp\030\005 \001(\005\".\n\016HPItemInfoSync\022\034\n\tit" +
      "emInfos\030\001 \003(\0132\t.ItemInfoB\031\n\027com.guaji.ga" +
      "me.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ItemInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ItemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemInfo_descriptor,
              new java.lang.String[] { "Id", "ItemId", "Count", "Status", "Exp", });
          internal_static_HPItemInfoSync_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPItemInfoSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPItemInfoSync_descriptor,
              new java.lang.String[] { "ItemInfos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
