// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerTitle.proto

package com.guaji.game.protocol;

public final class PlayerTitle {
  private PlayerTitle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TitleInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 titleIds = 1;
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    java.util.List<java.lang.Integer> getTitleIdsList();
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    int getTitleIdsCount();
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    int getTitleIds(int index);

    // required int32 titleId = 2;
    /**
     * <code>required int32 titleId = 2;</code>
     *
     * <pre>
     *当前称号已用称号Id，0是没有称号
     * </pre>
     */
    boolean hasTitleId();
    /**
     * <code>required int32 titleId = 2;</code>
     *
     * <pre>
     *当前称号已用称号Id，0是没有称号
     * </pre>
     */
    int getTitleId();
  }
  /**
   * Protobuf type {@code TitleInfo}
   */
  public static final class TitleInfo extends
      com.google.protobuf.GeneratedMessage
      implements TitleInfoOrBuilder {
    // Use TitleInfo.newBuilder() to construct.
    private TitleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TitleInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TitleInfo defaultInstance;
    public static TitleInfo getDefaultInstance() {
      return defaultInstance;
    }

    public TitleInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TitleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                titleIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              titleIds_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                titleIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                titleIds_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              titleId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          titleIds_ = java.util.Collections.unmodifiableList(titleIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_TitleInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_TitleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.PlayerTitle.TitleInfo.class, com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<TitleInfo> PARSER =
        new com.google.protobuf.AbstractParser<TitleInfo>() {
      public TitleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TitleInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TitleInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int32 titleIds = 1;
    public static final int TITLEIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> titleIds_;
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getTitleIdsList() {
      return titleIds_;
    }
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    public int getTitleIdsCount() {
      return titleIds_.size();
    }
    /**
     * <code>repeated int32 titleIds = 1;</code>
     *
     * <pre>
     *全部获得的
     * </pre>
     */
    public int getTitleIds(int index) {
      return titleIds_.get(index);
    }

    // required int32 titleId = 2;
    public static final int TITLEID_FIELD_NUMBER = 2;
    private int titleId_;
    /**
     * <code>required int32 titleId = 2;</code>
     *
     * <pre>
     *当前称号已用称号Id，0是没有称号
     * </pre>
     */
    public boolean hasTitleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 titleId = 2;</code>
     *
     * <pre>
     *当前称号已用称号Id，0是没有称号
     * </pre>
     */
    public int getTitleId() {
      return titleId_;
    }

    private void initFields() {
      titleIds_ = java.util.Collections.emptyList();
      titleId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTitleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < titleIds_.size(); i++) {
        output.writeInt32(1, titleIds_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, titleId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < titleIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(titleIds_.get(i));
        }
        size += dataSize;
        size += 1 * getTitleIdsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, titleId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.TitleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.PlayerTitle.TitleInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TitleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_TitleInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_TitleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.PlayerTitle.TitleInfo.class, com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder.class);
      }

      // Construct using com.guaji.game.protocol.PlayerTitle.TitleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        titleIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        titleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_TitleInfo_descriptor;
      }

      public com.guaji.game.protocol.PlayerTitle.TitleInfo getDefaultInstanceForType() {
        return com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance();
      }

      public com.guaji.game.protocol.PlayerTitle.TitleInfo build() {
        com.guaji.game.protocol.PlayerTitle.TitleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.PlayerTitle.TitleInfo buildPartial() {
        com.guaji.game.protocol.PlayerTitle.TitleInfo result = new com.guaji.game.protocol.PlayerTitle.TitleInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          titleIds_ = java.util.Collections.unmodifiableList(titleIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.titleIds_ = titleIds_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.titleId_ = titleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.PlayerTitle.TitleInfo) {
          return mergeFrom((com.guaji.game.protocol.PlayerTitle.TitleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.PlayerTitle.TitleInfo other) {
        if (other == com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance()) return this;
        if (!other.titleIds_.isEmpty()) {
          if (titleIds_.isEmpty()) {
            titleIds_ = other.titleIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTitleIdsIsMutable();
            titleIds_.addAll(other.titleIds_);
          }
          onChanged();
        }
        if (other.hasTitleId()) {
          setTitleId(other.getTitleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitleId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.PlayerTitle.TitleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.PlayerTitle.TitleInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 titleIds = 1;
      private java.util.List<java.lang.Integer> titleIds_ = java.util.Collections.emptyList();
      private void ensureTitleIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          titleIds_ = new java.util.ArrayList<java.lang.Integer>(titleIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getTitleIdsList() {
        return java.util.Collections.unmodifiableList(titleIds_);
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public int getTitleIdsCount() {
        return titleIds_.size();
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public int getTitleIds(int index) {
        return titleIds_.get(index);
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public Builder setTitleIds(
          int index, int value) {
        ensureTitleIdsIsMutable();
        titleIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public Builder addTitleIds(int value) {
        ensureTitleIdsIsMutable();
        titleIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public Builder addAllTitleIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTitleIdsIsMutable();
        super.addAll(values, titleIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 titleIds = 1;</code>
       *
       * <pre>
       *全部获得的
       * </pre>
       */
      public Builder clearTitleIds() {
        titleIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // required int32 titleId = 2;
      private int titleId_ ;
      /**
       * <code>required int32 titleId = 2;</code>
       *
       * <pre>
       *当前称号已用称号Id，0是没有称号
       * </pre>
       */
      public boolean hasTitleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 titleId = 2;</code>
       *
       * <pre>
       *当前称号已用称号Id，0是没有称号
       * </pre>
       */
      public int getTitleId() {
        return titleId_;
      }
      /**
       * <code>required int32 titleId = 2;</code>
       *
       * <pre>
       *当前称号已用称号Id，0是没有称号
       * </pre>
       */
      public Builder setTitleId(int value) {
        bitField0_ |= 0x00000002;
        titleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 titleId = 2;</code>
       *
       * <pre>
       *当前称号已用称号Id，0是没有称号
       * </pre>
       */
      public Builder clearTitleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        titleId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TitleInfo)
    }

    static {
      defaultInstance = new TitleInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TitleInfo)
  }

  public interface HPTitleInfoSyncSOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .TitleInfo titleInfo = 1;
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    boolean hasTitleInfo();
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    com.guaji.game.protocol.PlayerTitle.TitleInfo getTitleInfo();
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder getTitleInfoOrBuilder();

    // optional int32 titleChanged = 2;
    /**
     * <code>optional int32 titleChanged = 2;</code>
     */
    boolean hasTitleChanged();
    /**
     * <code>optional int32 titleChanged = 2;</code>
     */
    int getTitleChanged();
  }
  /**
   * Protobuf type {@code HPTitleInfoSyncS}
   *
   * <pre>
   *同步称号信息
   * </pre>
   */
  public static final class HPTitleInfoSyncS extends
      com.google.protobuf.GeneratedMessage
      implements HPTitleInfoSyncSOrBuilder {
    // Use HPTitleInfoSyncS.newBuilder() to construct.
    private HPTitleInfoSyncS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPTitleInfoSyncS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPTitleInfoSyncS defaultInstance;
    public static HPTitleInfoSyncS getDefaultInstance() {
      return defaultInstance;
    }

    public HPTitleInfoSyncS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPTitleInfoSyncS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = titleInfo_.toBuilder();
              }
              titleInfo_ = input.readMessage(com.guaji.game.protocol.PlayerTitle.TitleInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(titleInfo_);
                titleInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              titleChanged_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_HPTitleInfoSyncS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_HPTitleInfoSyncS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.class, com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.Builder.class);
    }

    public static com.google.protobuf.Parser<HPTitleInfoSyncS> PARSER =
        new com.google.protobuf.AbstractParser<HPTitleInfoSyncS>() {
      public HPTitleInfoSyncS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPTitleInfoSyncS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPTitleInfoSyncS> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .TitleInfo titleInfo = 1;
    public static final int TITLEINFO_FIELD_NUMBER = 1;
    private com.guaji.game.protocol.PlayerTitle.TitleInfo titleInfo_;
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    public boolean hasTitleInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    public com.guaji.game.protocol.PlayerTitle.TitleInfo getTitleInfo() {
      return titleInfo_;
    }
    /**
     * <code>required .TitleInfo titleInfo = 1;</code>
     */
    public com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder getTitleInfoOrBuilder() {
      return titleInfo_;
    }

    // optional int32 titleChanged = 2;
    public static final int TITLECHANGED_FIELD_NUMBER = 2;
    private int titleChanged_;
    /**
     * <code>optional int32 titleChanged = 2;</code>
     */
    public boolean hasTitleChanged() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 titleChanged = 2;</code>
     */
    public int getTitleChanged() {
      return titleChanged_;
    }

    private void initFields() {
      titleInfo_ = com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance();
      titleChanged_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTitleInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTitleInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, titleInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, titleChanged_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, titleInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, titleChanged_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPTitleInfoSyncS}
     *
     * <pre>
     *同步称号信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_HPTitleInfoSyncS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_HPTitleInfoSyncS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.class, com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.Builder.class);
      }

      // Construct using com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTitleInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (titleInfoBuilder_ == null) {
          titleInfo_ = com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance();
        } else {
          titleInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        titleChanged_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_HPTitleInfoSyncS_descriptor;
      }

      public com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS getDefaultInstanceForType() {
        return com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.getDefaultInstance();
      }

      public com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS build() {
        com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS buildPartial() {
        com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS result = new com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (titleInfoBuilder_ == null) {
          result.titleInfo_ = titleInfo_;
        } else {
          result.titleInfo_ = titleInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.titleChanged_ = titleChanged_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS) {
          return mergeFrom((com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS other) {
        if (other == com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS.getDefaultInstance()) return this;
        if (other.hasTitleInfo()) {
          mergeTitleInfo(other.getTitleInfo());
        }
        if (other.hasTitleChanged()) {
          setTitleChanged(other.getTitleChanged());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitleInfo()) {
          
          return false;
        }
        if (!getTitleInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.PlayerTitle.HPTitleInfoSyncS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .TitleInfo titleInfo = 1;
      private com.guaji.game.protocol.PlayerTitle.TitleInfo titleInfo_ = com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.guaji.game.protocol.PlayerTitle.TitleInfo, com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder, com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder> titleInfoBuilder_;
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public boolean hasTitleInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public com.guaji.game.protocol.PlayerTitle.TitleInfo getTitleInfo() {
        if (titleInfoBuilder_ == null) {
          return titleInfo_;
        } else {
          return titleInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public Builder setTitleInfo(com.guaji.game.protocol.PlayerTitle.TitleInfo value) {
        if (titleInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          titleInfo_ = value;
          onChanged();
        } else {
          titleInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public Builder setTitleInfo(
          com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder builderForValue) {
        if (titleInfoBuilder_ == null) {
          titleInfo_ = builderForValue.build();
          onChanged();
        } else {
          titleInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public Builder mergeTitleInfo(com.guaji.game.protocol.PlayerTitle.TitleInfo value) {
        if (titleInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              titleInfo_ != com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance()) {
            titleInfo_ =
              com.guaji.game.protocol.PlayerTitle.TitleInfo.newBuilder(titleInfo_).mergeFrom(value).buildPartial();
          } else {
            titleInfo_ = value;
          }
          onChanged();
        } else {
          titleInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public Builder clearTitleInfo() {
        if (titleInfoBuilder_ == null) {
          titleInfo_ = com.guaji.game.protocol.PlayerTitle.TitleInfo.getDefaultInstance();
          onChanged();
        } else {
          titleInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder getTitleInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTitleInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      public com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder getTitleInfoOrBuilder() {
        if (titleInfoBuilder_ != null) {
          return titleInfoBuilder_.getMessageOrBuilder();
        } else {
          return titleInfo_;
        }
      }
      /**
       * <code>required .TitleInfo titleInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.guaji.game.protocol.PlayerTitle.TitleInfo, com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder, com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder> 
          getTitleInfoFieldBuilder() {
        if (titleInfoBuilder_ == null) {
          titleInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.guaji.game.protocol.PlayerTitle.TitleInfo, com.guaji.game.protocol.PlayerTitle.TitleInfo.Builder, com.guaji.game.protocol.PlayerTitle.TitleInfoOrBuilder>(
                  titleInfo_,
                  getParentForChildren(),
                  isClean());
          titleInfo_ = null;
        }
        return titleInfoBuilder_;
      }

      // optional int32 titleChanged = 2;
      private int titleChanged_ ;
      /**
       * <code>optional int32 titleChanged = 2;</code>
       */
      public boolean hasTitleChanged() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 titleChanged = 2;</code>
       */
      public int getTitleChanged() {
        return titleChanged_;
      }
      /**
       * <code>optional int32 titleChanged = 2;</code>
       */
      public Builder setTitleChanged(int value) {
        bitField0_ |= 0x00000002;
        titleChanged_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 titleChanged = 2;</code>
       */
      public Builder clearTitleChanged() {
        bitField0_ = (bitField0_ & ~0x00000002);
        titleChanged_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPTitleInfoSyncS)
    }

    static {
      defaultInstance = new HPTitleInfoSyncS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPTitleInfoSyncS)
  }

  public interface ChooseTitleIdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 titleId = 1;
    /**
     * <code>required int32 titleId = 1;</code>
     */
    boolean hasTitleId();
    /**
     * <code>required int32 titleId = 1;</code>
     */
    int getTitleId();
  }
  /**
   * Protobuf type {@code ChooseTitleId}
   *
   * <pre>
   *选择称号
   * </pre>
   */
  public static final class ChooseTitleId extends
      com.google.protobuf.GeneratedMessage
      implements ChooseTitleIdOrBuilder {
    // Use ChooseTitleId.newBuilder() to construct.
    private ChooseTitleId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChooseTitleId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChooseTitleId defaultInstance;
    public static ChooseTitleId getDefaultInstance() {
      return defaultInstance;
    }

    public ChooseTitleId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChooseTitleId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              titleId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_ChooseTitleId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.PlayerTitle.internal_static_ChooseTitleId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.PlayerTitle.ChooseTitleId.class, com.guaji.game.protocol.PlayerTitle.ChooseTitleId.Builder.class);
    }

    public static com.google.protobuf.Parser<ChooseTitleId> PARSER =
        new com.google.protobuf.AbstractParser<ChooseTitleId>() {
      public ChooseTitleId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChooseTitleId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChooseTitleId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 titleId = 1;
    public static final int TITLEID_FIELD_NUMBER = 1;
    private int titleId_;
    /**
     * <code>required int32 titleId = 1;</code>
     */
    public boolean hasTitleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 titleId = 1;</code>
     */
    public int getTitleId() {
      return titleId_;
    }

    private void initFields() {
      titleId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTitleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, titleId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, titleId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.PlayerTitle.ChooseTitleId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.PlayerTitle.ChooseTitleId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChooseTitleId}
     *
     * <pre>
     *选择称号
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.PlayerTitle.ChooseTitleIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_ChooseTitleId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_ChooseTitleId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.PlayerTitle.ChooseTitleId.class, com.guaji.game.protocol.PlayerTitle.ChooseTitleId.Builder.class);
      }

      // Construct using com.guaji.game.protocol.PlayerTitle.ChooseTitleId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        titleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.PlayerTitle.internal_static_ChooseTitleId_descriptor;
      }

      public com.guaji.game.protocol.PlayerTitle.ChooseTitleId getDefaultInstanceForType() {
        return com.guaji.game.protocol.PlayerTitle.ChooseTitleId.getDefaultInstance();
      }

      public com.guaji.game.protocol.PlayerTitle.ChooseTitleId build() {
        com.guaji.game.protocol.PlayerTitle.ChooseTitleId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.PlayerTitle.ChooseTitleId buildPartial() {
        com.guaji.game.protocol.PlayerTitle.ChooseTitleId result = new com.guaji.game.protocol.PlayerTitle.ChooseTitleId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.titleId_ = titleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.PlayerTitle.ChooseTitleId) {
          return mergeFrom((com.guaji.game.protocol.PlayerTitle.ChooseTitleId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.PlayerTitle.ChooseTitleId other) {
        if (other == com.guaji.game.protocol.PlayerTitle.ChooseTitleId.getDefaultInstance()) return this;
        if (other.hasTitleId()) {
          setTitleId(other.getTitleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitleId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.PlayerTitle.ChooseTitleId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.PlayerTitle.ChooseTitleId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 titleId = 1;
      private int titleId_ ;
      /**
       * <code>required int32 titleId = 1;</code>
       */
      public boolean hasTitleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 titleId = 1;</code>
       */
      public int getTitleId() {
        return titleId_;
      }
      /**
       * <code>required int32 titleId = 1;</code>
       */
      public Builder setTitleId(int value) {
        bitField0_ |= 0x00000001;
        titleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 titleId = 1;</code>
       */
      public Builder clearTitleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        titleId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChooseTitleId)
    }

    static {
      defaultInstance = new ChooseTitleId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ChooseTitleId)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TitleInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TitleInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPTitleInfoSyncS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPTitleInfoSyncS_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChooseTitleId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChooseTitleId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PlayerTitle.proto\".\n\tTitleInfo\022\020\n\010titl" +
      "eIds\030\001 \003(\005\022\017\n\007titleId\030\002 \002(\005\"G\n\020HPTitleIn" +
      "foSyncS\022\035\n\ttitleInfo\030\001 \002(\0132\n.TitleInfo\022\024" +
      "\n\014titleChanged\030\002 \001(\005\" \n\rChooseTitleId\022\017\n" +
      "\007titleId\030\001 \002(\005B\031\n\027com.guaji.game.protoco" +
      "l"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TitleInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TitleInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TitleInfo_descriptor,
              new java.lang.String[] { "TitleIds", "TitleId", });
          internal_static_HPTitleInfoSyncS_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPTitleInfoSyncS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPTitleInfoSyncS_descriptor,
              new java.lang.String[] { "TitleInfo", "TitleChanged", });
          internal_static_ChooseTitleId_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ChooseTitleId_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChooseTitleId_descriptor,
              new java.lang.String[] { "TitleId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
