// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YaYa.proto

package com.guaji.game.protocol;

public final class YaYa {
  private YaYa() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HPExchangeGoldBeanPageRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 todayRechargeGold = 1;
    /**
     * <code>required int32 todayRechargeGold = 1;</code>
     *
     * <pre>
     * 今天充值的钻石数
     * </pre>
     */
    boolean hasTodayRechargeGold();
    /**
     * <code>required int32 todayRechargeGold = 1;</code>
     *
     * <pre>
     * 今天充值的钻石数
     * </pre>
     */
    int getTodayRechargeGold();

    // required int32 todayExchangeCostGold = 2;
    /**
     * <code>required int32 todayExchangeCostGold = 2;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    boolean hasTodayExchangeCostGold();
    /**
     * <code>required int32 todayExchangeCostGold = 2;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    int getTodayExchangeCostGold();

    // required int32 goldBean = 3;
    /**
     * <code>required int32 goldBean = 3;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    boolean hasGoldBean();
    /**
     * <code>required int32 goldBean = 3;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    int getGoldBean();
  }
  /**
   * Protobuf type {@code HPExchangeGoldBeanPageRet}
   *
   * <pre>
   * 返回兑换金豆页面信息
   * </pre>
   */
  public static final class HPExchangeGoldBeanPageRet extends
      com.google.protobuf.GeneratedMessage
      implements HPExchangeGoldBeanPageRetOrBuilder {
    // Use HPExchangeGoldBeanPageRet.newBuilder() to construct.
    private HPExchangeGoldBeanPageRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPExchangeGoldBeanPageRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPExchangeGoldBeanPageRet defaultInstance;
    public static HPExchangeGoldBeanPageRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPExchangeGoldBeanPageRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPExchangeGoldBeanPageRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              todayRechargeGold_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              todayExchangeCostGold_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              goldBean_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanPageRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanPageRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPExchangeGoldBeanPageRet> PARSER =
        new com.google.protobuf.AbstractParser<HPExchangeGoldBeanPageRet>() {
      public HPExchangeGoldBeanPageRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPExchangeGoldBeanPageRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPExchangeGoldBeanPageRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 todayRechargeGold = 1;
    public static final int TODAYRECHARGEGOLD_FIELD_NUMBER = 1;
    private int todayRechargeGold_;
    /**
     * <code>required int32 todayRechargeGold = 1;</code>
     *
     * <pre>
     * 今天充值的钻石数
     * </pre>
     */
    public boolean hasTodayRechargeGold() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 todayRechargeGold = 1;</code>
     *
     * <pre>
     * 今天充值的钻石数
     * </pre>
     */
    public int getTodayRechargeGold() {
      return todayRechargeGold_;
    }

    // required int32 todayExchangeCostGold = 2;
    public static final int TODAYEXCHANGECOSTGOLD_FIELD_NUMBER = 2;
    private int todayExchangeCostGold_;
    /**
     * <code>required int32 todayExchangeCostGold = 2;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    public boolean hasTodayExchangeCostGold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 todayExchangeCostGold = 2;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    public int getTodayExchangeCostGold() {
      return todayExchangeCostGold_;
    }

    // required int32 goldBean = 3;
    public static final int GOLDBEAN_FIELD_NUMBER = 3;
    private int goldBean_;
    /**
     * <code>required int32 goldBean = 3;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    public boolean hasGoldBean() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 goldBean = 3;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    public int getGoldBean() {
      return goldBean_;
    }

    private void initFields() {
      todayRechargeGold_ = 0;
      todayExchangeCostGold_ = 0;
      goldBean_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTodayRechargeGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayExchangeCostGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoldBean()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, todayRechargeGold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, todayExchangeCostGold_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, goldBean_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, todayRechargeGold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, todayExchangeCostGold_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldBean_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPExchangeGoldBeanPageRet}
     *
     * <pre>
     * 返回兑换金豆页面信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanPageRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanPageRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        todayRechargeGold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        todayExchangeCostGold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        goldBean_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanPageRet_descriptor;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet build() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet buildPartial() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet result = new com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.todayRechargeGold_ = todayRechargeGold_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.todayExchangeCostGold_ = todayExchangeCostGold_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.goldBean_ = goldBean_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet) {
          return mergeFrom((com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet other) {
        if (other == com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet.getDefaultInstance()) return this;
        if (other.hasTodayRechargeGold()) {
          setTodayRechargeGold(other.getTodayRechargeGold());
        }
        if (other.hasTodayExchangeCostGold()) {
          setTodayExchangeCostGold(other.getTodayExchangeCostGold());
        }
        if (other.hasGoldBean()) {
          setGoldBean(other.getGoldBean());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTodayRechargeGold()) {
          
          return false;
        }
        if (!hasTodayExchangeCostGold()) {
          
          return false;
        }
        if (!hasGoldBean()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.YaYa.HPExchangeGoldBeanPageRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 todayRechargeGold = 1;
      private int todayRechargeGold_ ;
      /**
       * <code>required int32 todayRechargeGold = 1;</code>
       *
       * <pre>
       * 今天充值的钻石数
       * </pre>
       */
      public boolean hasTodayRechargeGold() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 todayRechargeGold = 1;</code>
       *
       * <pre>
       * 今天充值的钻石数
       * </pre>
       */
      public int getTodayRechargeGold() {
        return todayRechargeGold_;
      }
      /**
       * <code>required int32 todayRechargeGold = 1;</code>
       *
       * <pre>
       * 今天充值的钻石数
       * </pre>
       */
      public Builder setTodayRechargeGold(int value) {
        bitField0_ |= 0x00000001;
        todayRechargeGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayRechargeGold = 1;</code>
       *
       * <pre>
       * 今天充值的钻石数
       * </pre>
       */
      public Builder clearTodayRechargeGold() {
        bitField0_ = (bitField0_ & ~0x00000001);
        todayRechargeGold_ = 0;
        onChanged();
        return this;
      }

      // required int32 todayExchangeCostGold = 2;
      private int todayExchangeCostGold_ ;
      /**
       * <code>required int32 todayExchangeCostGold = 2;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public boolean hasTodayExchangeCostGold() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 todayExchangeCostGold = 2;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public int getTodayExchangeCostGold() {
        return todayExchangeCostGold_;
      }
      /**
       * <code>required int32 todayExchangeCostGold = 2;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public Builder setTodayExchangeCostGold(int value) {
        bitField0_ |= 0x00000002;
        todayExchangeCostGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayExchangeCostGold = 2;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public Builder clearTodayExchangeCostGold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        todayExchangeCostGold_ = 0;
        onChanged();
        return this;
      }

      // required int32 goldBean = 3;
      private int goldBean_ ;
      /**
       * <code>required int32 goldBean = 3;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public boolean hasGoldBean() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 goldBean = 3;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public int getGoldBean() {
        return goldBean_;
      }
      /**
       * <code>required int32 goldBean = 3;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public Builder setGoldBean(int value) {
        bitField0_ |= 0x00000004;
        goldBean_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 goldBean = 3;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public Builder clearGoldBean() {
        bitField0_ = (bitField0_ & ~0x00000004);
        goldBean_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPExchangeGoldBeanPageRet)
    }

    static {
      defaultInstance = new HPExchangeGoldBeanPageRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPExchangeGoldBeanPageRet)
  }

  public interface HPExchangeGoldBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 count = 1;
    /**
     * <code>required int32 count = 1;</code>
     *
     * <pre>
     * 兑换数量
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>required int32 count = 1;</code>
     *
     * <pre>
     * 兑换数量
     * </pre>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code HPExchangeGoldBean}
   *
   * <pre>
   * 请求兑换金豆
   * </pre>
   */
  public static final class HPExchangeGoldBean extends
      com.google.protobuf.GeneratedMessage
      implements HPExchangeGoldBeanOrBuilder {
    // Use HPExchangeGoldBean.newBuilder() to construct.
    private HPExchangeGoldBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPExchangeGoldBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPExchangeGoldBean defaultInstance;
    public static HPExchangeGoldBean getDefaultInstance() {
      return defaultInstance;
    }

    public HPExchangeGoldBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPExchangeGoldBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.YaYa.HPExchangeGoldBean.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBean.Builder.class);
    }

    public static com.google.protobuf.Parser<HPExchangeGoldBean> PARSER =
        new com.google.protobuf.AbstractParser<HPExchangeGoldBean>() {
      public HPExchangeGoldBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPExchangeGoldBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPExchangeGoldBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    /**
     * <code>required int32 count = 1;</code>
     *
     * <pre>
     * 兑换数量
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 count = 1;</code>
     *
     * <pre>
     * 兑换数量
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.YaYa.HPExchangeGoldBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPExchangeGoldBean}
     *
     * <pre>
     * 请求兑换金豆
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.YaYa.HPExchangeGoldBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.YaYa.HPExchangeGoldBean.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBean.Builder.class);
      }

      // Construct using com.guaji.game.protocol.YaYa.HPExchangeGoldBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBean_descriptor;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBean getDefaultInstanceForType() {
        return com.guaji.game.protocol.YaYa.HPExchangeGoldBean.getDefaultInstance();
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBean build() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBean buildPartial() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBean result = new com.guaji.game.protocol.YaYa.HPExchangeGoldBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.YaYa.HPExchangeGoldBean) {
          return mergeFrom((com.guaji.game.protocol.YaYa.HPExchangeGoldBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.YaYa.HPExchangeGoldBean other) {
        if (other == com.guaji.game.protocol.YaYa.HPExchangeGoldBean.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.YaYa.HPExchangeGoldBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 count = 1;
      private int count_ ;
      /**
       * <code>required int32 count = 1;</code>
       *
       * <pre>
       * 兑换数量
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 count = 1;</code>
       *
       * <pre>
       * 兑换数量
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>required int32 count = 1;</code>
       *
       * <pre>
       * 兑换数量
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 count = 1;</code>
       *
       * <pre>
       * 兑换数量
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPExchangeGoldBean)
    }

    static {
      defaultInstance = new HPExchangeGoldBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPExchangeGoldBean)
  }

  public interface HPExchangeGoldBeanRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 todayExchangeCostGold = 1;
    /**
     * <code>required int32 todayExchangeCostGold = 1;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    boolean hasTodayExchangeCostGold();
    /**
     * <code>required int32 todayExchangeCostGold = 1;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    int getTodayExchangeCostGold();

    // required int32 goldBean = 2;
    /**
     * <code>required int32 goldBean = 2;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    boolean hasGoldBean();
    /**
     * <code>required int32 goldBean = 2;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    int getGoldBean();

    // required int32 msgType = 3;
    /**
     * <code>required int32 msgType = 3;</code>
     *
     * <pre>
     *消息发送类型(参考Const.YaYaMsgType)
     * </pre>
     */
    boolean hasMsgType();
    /**
     * <code>required int32 msgType = 3;</code>
     *
     * <pre>
     *消息发送类型(参考Const.YaYaMsgType)
     * </pre>
     */
    int getMsgType();
  }
  /**
   * Protobuf type {@code HPExchangeGoldBeanRet}
   *
   * <pre>
   * 返回兑换金豆信息
   * </pre>
   */
  public static final class HPExchangeGoldBeanRet extends
      com.google.protobuf.GeneratedMessage
      implements HPExchangeGoldBeanRetOrBuilder {
    // Use HPExchangeGoldBeanRet.newBuilder() to construct.
    private HPExchangeGoldBeanRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPExchangeGoldBeanRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPExchangeGoldBeanRet defaultInstance;
    public static HPExchangeGoldBeanRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPExchangeGoldBeanRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPExchangeGoldBeanRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              todayExchangeCostGold_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              goldBean_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPExchangeGoldBeanRet> PARSER =
        new com.google.protobuf.AbstractParser<HPExchangeGoldBeanRet>() {
      public HPExchangeGoldBeanRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPExchangeGoldBeanRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPExchangeGoldBeanRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 todayExchangeCostGold = 1;
    public static final int TODAYEXCHANGECOSTGOLD_FIELD_NUMBER = 1;
    private int todayExchangeCostGold_;
    /**
     * <code>required int32 todayExchangeCostGold = 1;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    public boolean hasTodayExchangeCostGold() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 todayExchangeCostGold = 1;</code>
     *
     * <pre>
     * 今天兑换消耗的钻石数
     * </pre>
     */
    public int getTodayExchangeCostGold() {
      return todayExchangeCostGold_;
    }

    // required int32 goldBean = 2;
    public static final int GOLDBEAN_FIELD_NUMBER = 2;
    private int goldBean_;
    /**
     * <code>required int32 goldBean = 2;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    public boolean hasGoldBean() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 goldBean = 2;</code>
     *
     * <pre>
     *金豆数量
     * </pre>
     */
    public int getGoldBean() {
      return goldBean_;
    }

    // required int32 msgType = 3;
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <code>required int32 msgType = 3;</code>
     *
     * <pre>
     *消息发送类型(参考Const.YaYaMsgType)
     * </pre>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 msgType = 3;</code>
     *
     * <pre>
     *消息发送类型(参考Const.YaYaMsgType)
     * </pre>
     */
    public int getMsgType() {
      return msgType_;
    }

    private void initFields() {
      todayExchangeCostGold_ = 0;
      goldBean_ = 0;
      msgType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTodayExchangeCostGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoldBean()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, todayExchangeCostGold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, goldBean_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, msgType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, todayExchangeCostGold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, goldBean_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPExchangeGoldBeanRet}
     *
     * <pre>
     * 返回兑换金豆信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.class, com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        todayExchangeCostGold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        goldBean_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.YaYa.internal_static_HPExchangeGoldBeanRet_descriptor;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet build() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet buildPartial() {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet result = new com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.todayExchangeCostGold_ = todayExchangeCostGold_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.goldBean_ = goldBean_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgType_ = msgType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet) {
          return mergeFrom((com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet other) {
        if (other == com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet.getDefaultInstance()) return this;
        if (other.hasTodayExchangeCostGold()) {
          setTodayExchangeCostGold(other.getTodayExchangeCostGold());
        }
        if (other.hasGoldBean()) {
          setGoldBean(other.getGoldBean());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTodayExchangeCostGold()) {
          
          return false;
        }
        if (!hasGoldBean()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.YaYa.HPExchangeGoldBeanRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 todayExchangeCostGold = 1;
      private int todayExchangeCostGold_ ;
      /**
       * <code>required int32 todayExchangeCostGold = 1;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public boolean hasTodayExchangeCostGold() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 todayExchangeCostGold = 1;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public int getTodayExchangeCostGold() {
        return todayExchangeCostGold_;
      }
      /**
       * <code>required int32 todayExchangeCostGold = 1;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public Builder setTodayExchangeCostGold(int value) {
        bitField0_ |= 0x00000001;
        todayExchangeCostGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayExchangeCostGold = 1;</code>
       *
       * <pre>
       * 今天兑换消耗的钻石数
       * </pre>
       */
      public Builder clearTodayExchangeCostGold() {
        bitField0_ = (bitField0_ & ~0x00000001);
        todayExchangeCostGold_ = 0;
        onChanged();
        return this;
      }

      // required int32 goldBean = 2;
      private int goldBean_ ;
      /**
       * <code>required int32 goldBean = 2;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public boolean hasGoldBean() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 goldBean = 2;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public int getGoldBean() {
        return goldBean_;
      }
      /**
       * <code>required int32 goldBean = 2;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public Builder setGoldBean(int value) {
        bitField0_ |= 0x00000002;
        goldBean_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 goldBean = 2;</code>
       *
       * <pre>
       *金豆数量
       * </pre>
       */
      public Builder clearGoldBean() {
        bitField0_ = (bitField0_ & ~0x00000002);
        goldBean_ = 0;
        onChanged();
        return this;
      }

      // required int32 msgType = 3;
      private int msgType_ ;
      /**
       * <code>required int32 msgType = 3;</code>
       *
       * <pre>
       *消息发送类型(参考Const.YaYaMsgType)
       * </pre>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 msgType = 3;</code>
       *
       * <pre>
       *消息发送类型(参考Const.YaYaMsgType)
       * </pre>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>required int32 msgType = 3;</code>
       *
       * <pre>
       *消息发送类型(参考Const.YaYaMsgType)
       * </pre>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000004;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgType = 3;</code>
       *
       * <pre>
       *消息发送类型(参考Const.YaYaMsgType)
       * </pre>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPExchangeGoldBeanRet)
    }

    static {
      defaultInstance = new HPExchangeGoldBeanRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPExchangeGoldBeanRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPExchangeGoldBeanPageRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPExchangeGoldBeanPageRet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPExchangeGoldBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPExchangeGoldBean_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPExchangeGoldBeanRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPExchangeGoldBeanRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nYaYa.proto\"g\n\031HPExchangeGoldBeanPageRe" +
      "t\022\031\n\021todayRechargeGold\030\001 \002(\005\022\035\n\025todayExc" +
      "hangeCostGold\030\002 \002(\005\022\020\n\010goldBean\030\003 \002(\005\"#\n" +
      "\022HPExchangeGoldBean\022\r\n\005count\030\001 \002(\005\"Y\n\025HP" +
      "ExchangeGoldBeanRet\022\035\n\025todayExchangeCost" +
      "Gold\030\001 \002(\005\022\020\n\010goldBean\030\002 \002(\005\022\017\n\007msgType\030" +
      "\003 \002(\005B\031\n\027com.guaji.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPExchangeGoldBeanPageRet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPExchangeGoldBeanPageRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPExchangeGoldBeanPageRet_descriptor,
              new java.lang.String[] { "TodayRechargeGold", "TodayExchangeCostGold", "GoldBean", });
          internal_static_HPExchangeGoldBean_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPExchangeGoldBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPExchangeGoldBean_descriptor,
              new java.lang.String[] { "Count", });
          internal_static_HPExchangeGoldBeanRet_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HPExchangeGoldBeanRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPExchangeGoldBeanRet_descriptor,
              new java.lang.String[] { "TodayExchangeCostGold", "GoldBean", "MsgType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
